### ISSUE TITLE
"Failed to run custom build command" for russimp-sys when adding russimp as a dependency

### ISSUE THREAD

**Issue by CravenWarrior3** [jkvargas/russimp-sys#19]
I didn't see any special instructions here or on the repository for russimp so I assumed everything related to assimp was going to be handled automatically. I'm using IntelliJ IDEA on Ubuntu 20.10 if that affects anything.

Error message:
```
ethan@ethan-gamingdesktop:/mnt/ssd/Projects/cw_building_editor$ cargo run
   Compiling russimp-sys v0.2.3
error: failed to run custom build command for `russimp-sys v0.2.3`

Caused by:
  process didn't exit successfully: `/mnt/ssd/Projects/cw_building_editor/target/debug/build/russimp-sys-595a9b8ede4516a9/build-script-build` (exit status: 101)
  --- stderr
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found
  wrapper.h:1:10: fatal error: 'assimp/cimport.h' file not found, err: true
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', /home/ethan/.cargo/registry/src/github.com-1ecc6299db9ec823/russimp-sys-0.2.3/build.rs:31:10
```

**Comment by jkvargas** [comment]
Hi mate,
Do you have installed libassimp?
If you did, which version did you install?
I suppose that you can do it with apt install libassimp, or something like that.

**Comment by CravenWarrior3** [comment]
Installing libassimp-dev fixed it. Would it be possible to mention dependencies like that anywhere?

**Comment by jkvargas** [comment]
Sure mate.
I will change the README.md as soon as I get some free time.
If you want, you can change it yourself.
I will approve the commit. :)
