### ISSUE TITLE
#Include <assimp/cexport.h> 

### ISSUE THREAD

**Issue by jl-beast** [jkvargas/russimp-sys#36]
I was recently writing up a project that uses russimp and by proxy russimp-sys. I noticed that in wrapper.h, cexport.h is not included. I was hoping, even though it would be unsafe, to use bindings from the cexport.h wrapper to help export some files that I load in after doing some work on them.

I was hoping to ask about the reasoning, would we be able to include?

**Comment by jkvargas** [comment]
hey @jl-beast, it is actually included https://github.com/jkvargas/russimp-sys/blob/4ac668ca1063fc903c8e11fa7eb0097892206180/wrapper.h#L4

is that what you wanted?

**Comment by jl-beast** [comment]
It seems to be. My issue that I am having is that I am unable to find <cexport.h> in russimp-sys.

I want to use aiExportScene even if it is unsafe.

**Comment by jkvargas** [comment]
hey man, should be possible
I pulled russimp-sys 2.0.1 and then, using jetbrains rustover I was able to import it.

`use russimp_sys::aiExportScene;
`

**Comment by jl-beast** [comment]
Seems like I had an older version. (feel kind of stupid that I didn't try and fix this first, been juggling a bunch of different projects so you will have to forgive me) 

Any way thanks. Will do if I have some time.
