### ISSUE TITLE
Use cmake + bindgen to generate buildings on the fly?

### ISSUE THREAD

**Issue by virtualritz** [jkvargas/russimp-sys#8]
It looks like `bindings.rs` was generated with `bindgen`.
I would suggest add `assimp` as a subrepo to this repo, run `CMake` via the `cmake` crate to build `assimp` and then run the `bindgen` builder on that, all from within `build.rs`.

I have written a few wrappers and I am happy to lend a hand with this. I am on a Mac so I will also help making sure building `russimp-sys`/`russimp` on that platform works.

I hang out on Discord lots under the same handle I have on github. Rust servers, Rust gamedev, Bevy etc. Hit me up there if you want to chat directly.

**Comment by jkvargas** [comment]
For sure, I will reach to you later Today.

**Comment by virtualritz** [comment]
On that note: [`assimp-sys`](https://github.com/Vurich/assimp-sys) does exactly that. Maybe use that repo as a template? Particularly the `build.rs`?

**Comment by jkvargas** [comment]
Will take a look as soon as I finish with the changes in russimp :)
